spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: SimpleAPI
  datasource:
    url: "${MYSQL_URL}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_PASSWORD}"
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: none
server:
  error:
    include-stacktrace: never

## SWAGGER ORDER ALPHABETICALLY
springdoc:
  swagger-ui:
    tagsSorter: alpha

secret:
  key: "${SECRET}"

token:
  expiration:
    time: "${EXPIRATION_MINUTES}"

